log_level: DEBUG
search_concurrency: 1
search_rate: 100
token_ttl: 24h
words_address: localhost:81
update_address: localhost:82
search_address: localhost:83
db_address: localhost:1234
jwt_secret: GOGOGOOOPHER
admin_name: admin
admin_password: password
api_server:
  address: localhost:80
  timeout: 5s
